title: VTEX IO Service Course
tagline: Building backend applications with VTEX IO
description: >-
  In this course, learn about the main possibilities of backend applications in
  VTEX IO. Export routes, handle events and connect with external and internal
  apps, to make your VTEX IO app even better and take the best out of VTEX
  infrastructure.
template:
  name: service-course
  repo: service-course-template
before:
  - body: 00-services.md
    title: Services in VTEX IO
    type: createIssue
steps:
  - title: Services in VTEX IO
    description: >-
      On this step, we have an overview of services in VTEX IO and brief
      explanation of backend possibilities
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: congrats_course.md
